name: gbshortner
description: "Shortner for GB Links"
publish_to: 'none'
version: 0.3.1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  equatable: any
  graphql_flutter: ^5.1.2
  get_it: any
  injectable: any
  injectable_generator: any
  http: ^1.2.1
  dio: ^5.4.3+1
  package_info_plus: ^8.0.0
  yaml: ^3.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
